### ISSUE TITLE
Distance Matrix with All Traps

### ISSUE THREAD

**Issue by nthaydt** [Hocking-Lab/cocanal-turtles#10]
Script = "Data/Coordinates.R"
Commit: 236a87e247eb172fb6c3bec229250afe6297687d
Contains code to create distance matrix using all traps
Example code found at https://github.com/clipo/Seriation/blob/master/R/distanceCalculations.R
AND https://github.com/clipo/Seriation/blob/master/R/distanceCalculations.R

As of 2/11/19 at 14:00, includes the following error:
"Error in while (abs(lamda - lamda.old) > 1e-11) { : argument is of length zero"

**Comment by djhocking** [comment]
fixed hopefully using the dist() function and then log transforming
