### ISSUE TITLE
starting locations per site

### ISSUE THREAD

**Issue by nthaydt** [Hocking-Lab/cocanal-turtles#12]
commit: 70faafb78cf9fb185ab9910b4c6a41d3884bb0c5

Code/MultiSessionModel.R
Beginning: line number 522

I tried to replace all 0's with a number from a random distribution determined by min and max distances per site. The code runs, but the replaced values all end up as 0...

- Natalie

**Comment by nthaydt** [comment]
Using a nested loop was creating the issue. Created a loop to calculate initial values of captures and another loop to calculate initial values for augments. Fixed.

**Comment by djhocking** [comment]
just went to look at it. Glad you got it fixed.
