### ISSUE TITLE
Sex Covariate - Error dimension mismatch line 39

### ISSUE THREAD

**Issue by nthaydt** [Hocking-Lab/cocanal-turtles#5]
@djhocking 
9ff98fc8637a1ce01b74111db939298a2566c236

**Comment by djhocking** [comment]
Can you please include what script you were running so I know where to look and maybe what part of the script if it's long?

**Comment by nthaydt** [comment]
Just created a new issue with the name of the script I’m working on. The issue title is “Sex Covariate Model - Initial Values for Sex” and the Script is named “SexCovariateModel.R” under the Code folder.


On Jan 15, 2019, at 3:44 PM, Daniel J. Hocking <notifications@github.com<mailto:notifications@github.com>> wrote:


Can you please include what script you were running so I know where to look and maybe what part of the script if it's long?

**Comment by djhocking** [comment]
working now
