### ISSUE TITLE
Sex Covariate Model Error

### ISSUE THREAD

**Issue by nthaydt** [Hocking-Lab/cocanal-turtles#7]
Commit 7c9fd18343acb580b9f53268b3ebed0d1081a604
"TurtleSCR_AllModels_SiteA.R"

Error: "object n_inds not found"

**Comment by djhocking** [comment]
Driving so I haven’t got a chance to look at the code. Usually that error is a result of not including that object in the data. It needs to be listed in the data that you passed to the rjags function.

**Comment by djhocking** [comment]
working currently
