### ISSUE TITLE
Sex Covariate Model - Initial Values for Sex

### ISSUE THREAD

**Issue by nthaydt** [Hocking-Lab/cocanal-turtles#8]
I've copied the section of code I'm running for this model into the file
"SexCovariateModel.R" in the Code folder.   (Commit 5c8d7ff70191ecf48e3a44b09f43617f3cce7788)

At this point, I'm getting the error:
"invalid parameters for chain 1:
non-numeric initial values supplied for variable(s) Sex"

The initial sex values are all NA's (pg. 211 in SCR textbook) which might be the issue, so I think I need to provide numeric initial values for sex somehow.

- Natalie

**Comment by djhocking** [comment]
I decided for that variable to allow JAGS to set the inits itself as a quick fix then fixed some issues with changes to alpha0 and alpha1. It's all working now.
